defaultScriptName = 'job.pbs'
defaultCores = 1
defaultWallTime = '01:00:00'
defaultDistribMem = 1 # gigabytes
defaultSMPMem = 3 # gigabytes
defaultSameDir = 'y'
defaultReceiveMail = 'y'
defaultFileOverwrite = 'n'
defaultJobName = ''
defaultIsSMP = 'n'
defaultCommand = ''
defaultModules = ''
